"use client";

import { useState } from "react";

type IconName = "grid" | "ticket" | "scan" | "settings" | "help" | "shield" | "plus" | "arrow" | "check" | "pause" | "more" | "lock";

function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const p: Record<IconName, React.ReactNode> = {
    grid: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    ticket: <><path d="M20 12a2.5 2.5 0 0 0 0-5V5.5A1.5 1.5 0 0 0 18.5 4h-13A1.5 1.5 0 0 0 4 5.5V7a2.5 2.5 0 0 0 0 5v1.5A1.5 1.5 0 0 0 5.5 15h13a1.5 1.5 0 0 0 1.5-1.5V12Z"/><path d="M12 4v2M12 8v2M12 12v2"/></>,
    scan: <><path d="M3 7V5a2 2 0 0 1 2-2h2M17 3h2a2 2 0 0 1 2 2v2M21 17v2a2 2 0 0 1-2 2h-2M7 21H5a2 2 0 0 1-2-2v-2"/><path d="M7 12h10M12 7v10"/></>,
    shield: <><path d="M12 3 20 6v5c0 5-3.4 8.2-8 10-4.6-1.8-8-5-8-10V6l8-3Z"/><path d="m8.5 12 2.2 2.2 4.8-5"/></>,
    plus: <><path d="M12 5v14M5 12h14"/></>, arrow: <><path d="M5 12h14M13 6l6 6-6 6"/></>, check: <path d="m5 12 4 4L19 6"/>, pause: <><rect x="6" y="5" width="4" height="14" rx="1"/><rect x="14" y="5" width="4" height="14" rx="1"/></>,
    more: <><circle cx="5" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="12" cy="12" r="1" fill="currentColor" stroke="none"/><circle cx="19" cy="12" r="1" fill="currentColor" stroke="none"/></>, lock: <><rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>, settings: <><circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 1-2v-2a2 2 0 0 0-1-2l-1-.4a7 7 0 0 0-1-1.7l.3-1a2 2 0 0 0-1-1.7l-2-.9a2 2 0 0 0-2 .4l-.7.7a7 7 0 0 0-2 0l-.7-.7a2 2 0 0 0-2-.4l-2 .9a2 2 0 0 0-1 1.7l.3 1a7 7 0 0 0-1 1.7L3 9a2 2 0 0 0-1 2v2a2 2 0 0 0 1 2l1 .4a7 7 0 0 0 1 1.7l-.3 1a2 2 0 0 0 1 1.7l2 .9a2 2 0 0 0 2-.4l.7-.7a7 7 0 0 0 2 0l.7.7a2 2 0 0 0 2 .4l2-.9a2 2 0 0 0 1-1.7l-.3-1a7 7 0 0 0 1-1.7L19 15Z"/></>, help: <><circle cx="12" cy="12" r="9"/><path d="M9.7 9a2.4 2.4 0 1 1 4.2 1.6c-.8.8-1.9 1.2-1.9 2.4M12 16.5h.01"/></>
  };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>;
}

const nav = [{ label: "Overview", icon: "grid" as IconName }, { label: "Issue passes", icon: "ticket" as IconName }, { label: "Verify redemption", icon: "scan" as IconName }];

export default function Home() {
  const [active, setActive] = useState("Overview"); const [open, setOpen] = useState(true); const [recipient, setRecipient] = useState(""); const [notice, setNotice] = useState(""); const [verified, setVerified] = useState(false);
  const toast = (s: string) => { setNotice(s); window.setTimeout(() => setNotice(""), 2800); };
  const issue = () => { if (!recipient.trim()) return toast("Add a reference label before issuing."); setRecipient(""); toast("Private pass issued. Secret stays with recipient."); };
  return <main className="app-shell">
    <aside className="sidebar"><div className="brand-lockup"><div className="brand-mark"><Icon name="shield" size={20}/></div><div><strong>Dignity Pass</strong><span>private aid network</span></div></div><div className="workspace-label">WORKSPACE</div><div className="workspace-switcher"><i/>Relief Network <b>⌄</b></div><nav aria-label="Primary navigation">{nav.map(n => <button key={n.label} className={`nav-item ${active === n.label ? "selected" : ""}`} onClick={() => setActive(n.label)}><Icon name={n.icon}/><span>{n.label}</span>{n.label === "Issue passes" && <em>24</em>}</button>)}</nav><div className="sidebar-bottom"><button className="nav-item"><Icon name="settings"/><span>Campaign settings</span></button><button className="nav-item"><Icon name="help"/><span>Help center</span></button><div className="network-card"><div><i/>Midnight Preprod <b>LIVE</b></div><span>Proofs settle privately</span></div><div className="profile"><div className="avatar">RN</div><div><strong>Relief Network</strong><span>Agency workspace</span></div><Icon name="more" size={17}/></div></div></aside>
    <section className="content-area"><header className="topbar"><div className="breadcrumbs"><span>Relief Network</span><b>/</b><strong>{active}</strong></div><div className="top-actions"><span className="privacy-pill"><Icon name="lock" size={14}/> private by default</span><button className="icon-button" aria-label="More options"><Icon name="more"/></button></div></header><div className="content-scroll"><div className="page-heading"><div><p className="eyebrow">TUESDAY · 14 MAY 2024</p><h1>{active === "Overview" ? "Good morning, Relief Network." : active}</h1><p className="subheading">One place to issue aid without asking people to expose their story.</p></div><button className="primary-button" onClick={() => setActive("Issue passes")}><Icon name="plus" size={17}/> Issue new pass</button></div>
      {active === "Overview" && <Overview open={open} setOpen={setOpen} toast={toast}/>} {active === "Issue passes" && <div className="flow-layout"><section className="panel flow-card"><div className="flow-step"><span>01</span><div><p className="section-kicker">NEW PRIVATE PASS</p><h2>Prepare a pass</h2><p className="flow-copy">Create a one-time coupon for an eligible person. Their identity never enters this system.</p></div></div><label htmlFor="ref">Internal reference <small>optional</small></label><input id="ref" value={recipient} onChange={e => setRecipient(e.target.value)} placeholder="e.g. household 0248"/><span className="field-note">For your records only. Never a name, address, or eligibility detail.</span><button className="primary-button full" onClick={issue}><Icon name="ticket" size={17}/> Generate private pass <Icon name="arrow" size={16}/></button></section><section className="side-explainer"><div className="explainer-icon"><Icon name="lock" size={20}/></div><p className="section-kicker">WHAT THE RECIPIENT GETS</p><h3>A pass they can use with dignity.</h3><p>Only their wallet holds the secret needed to prove eligibility. Shops see a green check — nothing more.</p><div className="proof-row"><Icon name="shield" size={16}/> Zero-knowledge proof</div><div className="proof-row"><Icon name="check" size={16}/> One-time redemption</div></section></div>}
      {active === "Verify redemption" && <div className="verify-layout"><section className={`verify-result ${verified ? "valid" : ""}`}><div className="verify-symbol">{verified ? <Icon name="check" size={34}/> : <Icon name="scan" size={34}/>}</div><p className="section-kicker">SHOP VERIFICATION</p><h2>{verified ? "Pass is valid" : "Ready to verify"}</h2><p>{verified ? "This coupon is eligible and has not been used before. No identity revealed." : "Scan or paste a private pass proof to check it against the Midnight ledger."}</p>{verified ? <button className="secondary-button" onClick={() => setVerified(false)}>Verify another pass</button> : <button className="primary-button" onClick={() => { setVerified(true); toast("Proof verified. Coupon is valid and unused."); }}><Icon name="scan" size={17}/> Run demo verification</button>}</section><section className="panel verify-info"><p className="section-kicker">WHAT IS SHARED</p><h3>Proof, not personal data.</h3><div className="shared-list"><div><Icon name="check" size={16}/> Coupon is issued <small>verified privately</small></div><div><Icon name="check" size={16}/> Coupon is unused <small>nullifier checked</small></div><div className="private"><Icon name="lock" size={16}/> Person&apos;s identity <small>never disclosed</small></div></div><div className="ledger-chip"><i/> Midnight ledger <b>synced</b></div></section></div>}
    </div></section>{notice && <div className="toast"><span><Icon name="check" size={14}/></span>{notice}</div>}</main>;
}

function Overview({ open, setOpen, toast }: { open: boolean; setOpen: (v: boolean) => void; toast: (s: string) => void }) { return <><section className="campaign-banner"><div className="banner-icon"><Icon name="shield" size={24}/></div><div className="banner-copy"><div className="banner-title"><i/> Winter food support <b>OPEN</b></div><p>Active campaign · expires 30 Jun 2024</p></div><button className="text-button" onClick={() => { setOpen(!open); toast(open ? "Campaign paused." : "Campaign resumed."); }}>{open ? <><Icon name="pause" size={15}/> Pause campaign</> : <><Icon name="check" size={15}/> Resume campaign</>}</button><button className="icon-button faint" aria-label="Campaign menu"><Icon name="more"/></button></section><section className="stats-grid"><Stat label="Passes issued" value="248" detail="of 500 available" trend="+18%"/><Stat label="Redeemed" value="186" detail="75% redemption rate" trend="+12%" mint/><Stat label="Still available" value="62" detail="across 3 partner shops" trend="25%"/></section><div className="main-grid"><section className="panel activity-panel"><PanelHead kicker="RECENT ACTIVITY" title="Pass movement"/><div className="activity-chart"><div className="chart-y"><span>60</span><span>40</span><span>20</span><span>0</span></div><div className="chart-body"><div className="grid-lines"><i/><i/><i/><i/></div><div className="bars">{[32,44,38,55,48,66,52,74,61,79,68,91].map((h,i) => <i key={i} className={i === 11 ? "today" : ""} style={{height: `${h}%`}}/>)}</div><div className="chart-x"><span>03 May</span><span>07 May</span><span>11 May</span><span>14 May</span></div></div></div><div className="legend"><span><i/>Issued</span><span><i/>Redeemed</span><small>Last 12 days</small></div></section><section className="panel redemption-panel"><PanelHead kicker="REDEMPTION RATE" title="Three in four passes used"/><div className="donut-wrap"><div className="donut"><div><strong>75<span>%</span></strong><small>redeemed</small></div></div><div className="donut-details"><div><strong>186</strong><span>Redeemed</span></div><div><strong>62</strong><span>Available</span></div><div><strong>0</strong><span>Invalidated</span></div></div></div><div className="success-note"><Icon name="check" size={15}/> All partner shops synced <small>just now</small></div></section></div><section className="panel table-panel"><PanelHead kicker="PARTNER SHOPS" title="Where passes are accepted"/><div className="partner-table"><div className="table-row table-head"><span>PARTNER</span><span>REDEEMED</span><span>AVAILABLE</span><span>STATUS</span><span/></div><Partner name="Green Basket Cooperative" area="Kampala Central" redeemed="84" available="16"/><Partner name="Mirembe Community Shop" area="Kisenyi" redeemed="61" available="27"/><Partner name="Hope Market" area="Makindye" redeemed="41" available="19"/></div></section></>; }
function PanelHead({ kicker, title }: { kicker: string; title: string }) { return <div className="panel-heading"><div><p className="section-kicker">{kicker}</p><h2>{title}</h2></div><button className="small-button">View all <Icon name="arrow" size={14}/></button></div>; }
function Stat({ label, value, detail, trend, mint = false }: { label: string; value: string; detail: string; trend: string; mint?: boolean }) { return <div className={`stat-card ${mint ? "mint-card" : ""}`}><div className="stat-top"><span>{label}</span><b>{trend}</b></div><strong>{value}</strong><small>{detail}</small><div className="mini-spark">{[30,42,35,60,54,76,100].map((h,i) => <i key={i} style={{height: `${h}%`}}/>)}</div></div>; }
function Partner({ name, area, redeemed, available }: { name: string; area: string; redeemed: string; available: string }) { return <div className="table-row"><div className="partner-name"><span><Icon name="grid" size={14}/></span><strong>{name}<small>{area}</small></strong></div><span>{redeemed}</span><span>{available}</span><span><i/> Active</span><button className="icon-button faint" aria-label={`More options for ${name}`}><Icon name="more" size={16}/></button></div>; }
