'use client';

import { useCallback, useState } from 'react';
import Link from 'next/link';
import { createConnectedSession, detectWallet, MIDNIGHT_NETWORK, pollForState, type ConnectedSession } from '@/lib/midnight';
import { deployDignityPass } from '@/lib/dignity-pass';

const DEMO_CAMPAIGN = '1111111111111111111111111111111111111111111111111111111111111111';
const DEMO_AGENCY = '2222222222222222222222222222222222222222222222222222222222222222';

export default function DeployPage() {
  const [session, setSession] = useState<ConnectedSession | null>(null); const [address, setAddress] = useState(''); const [busy, setBusy] = useState(false); const [status, setStatus] = useState(''); const [error, setError] = useState('');
  const connect = useCallback(async () => { setBusy(true); setError(''); try { const wallet = await detectWallet(); if (!wallet) throw new Error('1AM wallet not detected. Install the 1AM browser extension.'); const api = await wallet.connect(MIDNIGHT_NETWORK); setSession(await createConnectedSession(api, '/zk/dignity-pass/')); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }, []);
  const deploy = useCallback(async () => { if (!session) return; setBusy(true); setError(''); try { setStatus('Creating deployment with 1AM…'); const deployed = await deployDignityPass(session, DEMO_CAMPAIGN, DEMO_AGENCY, BigInt(0), BigInt(500)); setAddress(deployed); setStatus('Submitted through 1AM. Waiting for preprod indexer…'); await pollForState(session.config.indexerUri, deployed, 120); setStatus('Contract deployed and indexed on Midnight preprod.'); } catch (e) { setError(e instanceof Error ? e.message : String(e)); setStatus(''); } finally { setBusy(false); } }, [session]);
  return <main className="deploy-page"><Link className="deploy-back" href="/">← Back to dashboard</Link><div className="deploy-shell"><div className="deploy-kicker"><span className="deploy-mark">✦</span> MIDNIGHT PREPROD · 1AM</div><h1>Deploy Dignity Pass</h1><p className="deploy-lede">Put private aid verification on chain. Deployment is signed, proved, balanced, and submitted by your 1AM browser extension.</p><div className="deploy-trust"><span>NETWORK <b>preprod</b></span><span>PROVING <b>1AM ProofStation</b></span><span>FUNDING <b>Wallet flow only</b></span></div>{!session && <section className="deploy-card"><div className="deploy-step">01</div><div><h2>Connect 1AM</h2><p>Use a wallet connected to Midnight preprod. No funded server-side deployer is used.</p><button className="deploy-button" onClick={connect} disabled={busy}>{busy ? 'Connecting…' : 'Connect 1AM wallet →'}</button></div></section>}{session && !address && <section className="deploy-card"><div className="deploy-step">02</div><div><h2>Deploy campaign contract</h2><p>Demo campaign initializes with 500 available passes and no expiry. Change constructor values in the DApp integration before production use.</p><div className="config-line"><span>Campaign ID</span><code>{DEMO_CAMPAIGN.slice(0, 12)}…</code></div><div className="config-line"><span>Network</span><code>{session.config.networkId}</code></div><button className="deploy-button" onClick={deploy} disabled={busy}>{busy ? status || 'Deploying…' : 'Deploy through 1AM →'}</button></div></section>}{status && <p className="deploy-status"><i/> {status}</p>}{error && <p className="deploy-error">{error}</p>}{address && <section className="address-card"><div className="success-icon">✓</div><div><p className="deploy-kicker">DEPLOYMENT CONFIRMED</p><h2>Contract is live</h2><p>Save this address for agency operations and partner verification.</p><code>{address}</code><button className="copy-address" onClick={() => navigator.clipboard?.writeText(address)}>Copy address</button></div></section>}<p className="deploy-footnote">Private proving happens through the connected 1AM provider. This page does not start or require a local proof server.</p></div></main>;
}
